TRUNCATE TABLE aqm_configuration;
INSERT INTO `aqm_configuration` (`data`, `content`) VALUES
('device_id', 'TRUSUR'),
('server', '127.0.0.1'),
('sta_id', 'TRUSUR'),
('sta_nama', 'TRUSUR'),
('sta_alamat', ''),
('sta_kota', ''),
('sta_prov', ''),
('sta_lat', '-6.0'),
('sta_lon', '106.0'),
('com_pm10', '/dev/ttyUSB999'),
('baud_pm10', '9600'),
('com_pm25', '/dev/ttyUSB999'),
('baud_pm25', '9600'),
('com_hc', '/dev/ttyUSB999'),
('baud_hc', '9600'),
('com_ws', '/dev/ttyUSB999'),
('baud_ws', '19200'),
('com_airmar', '/dev/ttyUSB999'),
('baud_airmar', '4800'),
('controller', '/dev/ttyACM999'),
('controller_baud', '9600'),
('com_modem', '/dev/ttyUSB999'),
('baud_modem', '115200'),
('pump_interval', '120'),
('pump_state', '1'),
('pump_last', '0000-00-00 00:00:00'),
('pump_control', '1'),
('com_pump_pwm', '/dev/ttyUSB999'),
('baud_pump_pwm', '9600'),
('pump_speed', '80'),
('data_interval', '30'),
('graph_interval', '0'),
('is_sampling', '0'),
('sampler_operator_name', ''),
('id_sampling', ''),
('start_sampling', '0'),
('e_pm10', '1'),
('e_pm25', '0'),
('e_so2', '1'),
('e_co', '1'),
('e_o3', '1'),
('e_no2', '1'),
('e_hc', '0'),
('e_ws', '1'),
('e_wd', '1'),
('e_humidity', '0'),
('e_temperature', '1'),
('e_pressure', '1'),
('e_sr', '0'),
('e_voc', '1'),
('e_nh3', '0'),
('e_rain_intensity', '0'),
('e_no', '0'),
('gas_simulation', '1'),
('weather_simulation', '1'),
('weather_city_id', '1642911');

DROP TABLE IF EXISTS `aqm_sensor_values`;
CREATE TABLE `aqm_sensor_values` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `AIN0` double DEFAULT '0',
  `AIN1` double DEFAULT '0',
  `AIN2` double DEFAULT '0',
  `AIN3` double DEFAULT '0',
  `AIN4` double DEFAULT '0',
  `AIN5` double DEFAULT '0',
  `AIN6` double DEFAULT '0',
  `AIN7` double DEFAULT '0',
  `HC` double DEFAULT '0',
  `PM25` varchar(255) DEFAULT '0',
  `PM10` varchar(255) DEFAULT '0',
  `WS` text DEFAULT '0',
  `xtimestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO aqm_sensor_values (id) VALUES (1);

DROP TABLE IF EXISTS `aqm_data`;
CREATE TABLE `aqm_data` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `id_stasiun` varchar(50) NOT NULL,
  `waktu` datetime NOT NULL,
  `pm10` double DEFAULT '0',
  `pm25` double DEFAULT '0',
  `so2` double DEFAULT '0',
  `co` double DEFAULT '0',
  `o3` double DEFAULT '0',
  `no2` double DEFAULT '0',
  `hc` double DEFAULT '0',
  `ws` double DEFAULT '0',
  `wd` double DEFAULT '0',
  `humidity` double DEFAULT '0',
  `temperature` double DEFAULT '0',
  `pressure` double DEFAULT '0',
  `sr` double DEFAULT '0',
  `sent` int(11) DEFAULT '0',
  `voc` double DEFAULT '0',
  `nh3` double DEFAULT '0',
  `rain_intensity` double DEFAULT '0',
  `h2s` double DEFAULT '0',
  `cs2` double DEFAULT '0',
  `no` double DEFAULT '0',
  `stat_pm10` tinyint(4) DEFAULT 1,
  `stat_so2` tinyint(4) DEFAULT 1,
  `stat_co` tinyint(4) DEFAULT 1,
  `stat_o3` tinyint(4) DEFAULT 1,
  `stat_no2` tinyint(4) DEFAULT 1,
  `sent2` int(11) DEFAULT 0,
  `sampler_operator_name` varchar(50) NOT NULL DEFAULT '',
  `id_sampling` varchar(200) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;